'use strict'

const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.join(__dirname, '..')
const html = fs.readFileSync(path.join(ROOT, 'public', 'index.html'), 'utf8')
const app = fs.readFileSync(path.join(ROOT, 'public', 'app.js'), 'utf8')
const styles = fs.readFileSync(path.join(ROOT, 'public', 'styles.css'), 'utf8')
const activity = fs.readFileSync(path.join(ROOT, 'android', 'app', 'src', 'main', 'java', 'com', 'dshremote', 'app', 'MainActivity.java'), 'utf8')
const manifest = fs.readFileSync(path.join(ROOT, 'android', 'app', 'src', 'main', 'AndroidManifest.xml'), 'utf8')

test('设置页提供 Android 功能测试和 ASR 日志操作', () => {
  assert.match(html, /data-settings-group="tests"/)
  assert.match(html, /id="settings-page-tests"/)
  assert.match(html, /id="btn-asr-test-start"/)
  assert.match(html, /id="btn-asr-test-stop"/)
  assert.match(html, /id="btn-asr-test-copy"/)
  assert.match(html, /id="btn-asr-test-permission"/)
  assert.match(html, /id="btn-asr-test-engine"/)
  assert.match(html, /id="asr-test-log"/)
  assert.match(styles, /\.feature-test-shell/)
  assert.match(styles, /\.feature-test-log/)
})

test('ASR 测试只通过 Android 原生桥运行并在前端保留可复制诊断日志', () => {
  assert.match(app, /window\.NativeAsrTest/)
  assert.match(app, /window\.__dshAsrEvent = asrTestEvent/)
  assert.match(app, /function asrTestReport\(\)/)
  assert.match(app, /copyText\(asrTestReport\(\)\)/)
  assert.match(app, /settings\.asrTestConsent/)
  assert.match(app, /settings\.asrTestWebUnsupported/)
  assert.match(app, /openAsrPermissionSettings/)
  assert.match(app, /settings\.asrTestPermissionError/)
  assert.match(app, /openAsrEngineSettings/)
  assert.match(app, /const SETTINGS_GROUPS = \['general', 'model', 'tests'/)
})

test('Android ASR 桥接包含权限、系统服务枚举、partial/final/error 和 session 恢复日志', () => {
  assert.match(manifest, /android\.permission\.RECORD_AUDIO/)
  assert.match(manifest, /android\.speech\.RecognitionService/)
  assert.match(activity, /addJavascriptInterface\(asrTestBridge, "NativeAsrTest"\)/)
  assert.match(activity, /requestPermissions\(new String\[\]\{Manifest\.permission\.RECORD_AUDIO\}/)
  assert.match(activity, /openAsrPermissionSettings/)
  assert.match(activity, /openAsrEngineSettings/)
  assert.match(activity, /Settings\.ACTION_VOICE_INPUT_SETTINGS/)
  assert.match(activity, /recordAudioAppOp/)
  assert.match(activity, /microphoneMuted/)
  assert.match(activity, /RecognizerIntent\.EXTRA_CALLING_PACKAGE/)
  assert.match(activity, /SpeechRecognizer\.isRecognitionAvailable/)
  assert.match(activity, /SpeechRecognizer\.isOnDeviceRecognitionAvailable/)
  assert.match(activity, /SpeechRecognizer\.createSpeechRecognizer/)
  assert.match(activity, /RecognizerIntent\.EXTRA_PARTIAL_RESULTS, true/)
  assert.match(activity, /onPartialResults\(Bundle results\)/)
  assert.match(activity, /onResults\(Bundle results\)/)
  assert.match(activity, /onError\(int error\)/)
  assert.match(activity, /destroyRecognizer\(\)/)
  assert.match(activity, /MAX_RESTARTS = 12/)
  assert.match(activity, /emit\("summary", buildSummary\(reason\)\)/)
})
